story_5/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='story_5'
urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('schedule/', schedule, name='schedule'),
    path('schedule/add_schedule/', add_schedule, name='add_schedule'),
    path('deleteList/<int:identity>/', deleteList, name='deleteList'),
]

story_7/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='story_7'
urlpatterns = [
    path('', portofolio, name='portofolio'),
]

story_8/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='story_8'
urlpatterns = [
    path('', search_book, name='search_book'),
    path('search/<title>', search, name='search'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_5.urls')),
    path('portofolio/', include('story_7.urls')),
    path('search_book/', include('story_8.urls')),
]

story_5/models.py
from django.utils import timezone
from datetime import datetime, date
from django.db import models

class Schedule(models.Model):
    nama_kegiatan = models.CharField(max_length=30)
    hari = models.CharField(max_length=30)
    tanggal = models.DateField() #datefield karena model tidak ada datetimefield
    jam = models.TimeField()
    tempat = models.CharField(max_length=30)
    kategori = models.CharField(max_length=30)

    def __str__(self):
        return self.nama_kegiatan

story_7/models.py
from django.db import models

# Create your models here.

story_8/models.py
from django.db import models

# Create your models here.

story_5/forms.py
from django import forms
from .models import Schedule

class Add_Schedule(forms.Form):

    attrs_nama_kegiatan = {
        'id': 'nama',
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Kerja',
    }

    attrs_hari = {
        'id': 'hari',
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Senin',
    }

    attrs_tanggal = {
        'id': 'tanggal',
        'type': 'date',
        'class': 'form-control',
    }

    attrs_jam = {
        'id': 'jam',
        'type': 'time',
        'class': 'form-control',
    }

    attrs_tempat = {
        'id': 'tempat',
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Universitas Indonesia'
    }

    attrs_kategori = {
        'id': 'kategori',
        'type': 'text',
        'class': 'form-control',
        'placeholder': 'Belajar PPW'
    }


    nama_kegiatan = forms.CharField(max_length=30, widget = forms.TextInput(attrs=attrs_nama_kegiatan)) #CharField, TextInput
    hari = forms.CharField(max_length=30, widget = forms.TextInput(attrs=attrs_hari)) #DateField, TextInput
    tanggal = forms.DateTimeField(widget = forms.DateInput(attrs=attrs_tanggal)) #DateTimeField, DateInput
    jam = forms.TimeField(widget = forms.TimeInput(attrs=attrs_jam)) #TimeField, TimeInput
    tempat = forms.CharField(max_length=30, widget = forms.TextInput(attrs=attrs_tempat)) #CharField, TextInput
    kategori = forms.CharField(max_length=30, widget = forms.TextInput(attrs=attrs_kategori)) #CharField, TextInput

story_5/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime, date
from .forms import *
from .models import *
from django.urls import reverse

# Create your views here.
def index(request):
	response = {}
	return render(request, 'index.html', response)

def contact(request):
	response = {}
	return render(request, 'contact.html', response)

def schedule(request): 
    schd = Schedule.objects.all()
    return render(request, 'schedule.html', {'table' : schd})


def add_schedule(request):
    if request.method == 'POST':
        form = Add_Schedule(request.POST)
        if form.is_valid():
            schd = Schedule.objects.all()
            nama = form.cleaned_data["nama_kegiatan"]
            hari = form.cleaned_data["hari"]
            tanggal = form.cleaned_data["tanggal"]
            jam = form.cleaned_data["jam"]
            tempat = form.cleaned_data["tempat"]
            kategori = form.cleaned_data["kategori"]

            jadwal = Schedule(nama_kegiatan = nama, hari= hari, tanggal=tanggal, jam=jam, tempat=tempat, kategori=kategori)
            jadwal.save()
            return render(request, 'schedule.html', {'table' : schd})
            # return HttpResponseRedirect(reverse('schedule'))
        else:
            return HttpResponseRedirect('add_schedule')
    else:
        form = Add_Schedule()
        return render(request, 'add_schedule.html', {'form' : form}) 
    

def deleteList(request, identity):
    Schedule.objects.get(id = identity).delete()
    # return HttpResponseRedirect(reverse('schedule'))

    # Schedule.objects.get(id = identity).delete()
    # form = Add_Schedule(request.POST)
    # return HttpResponseRedirect(reverse('schedule')) 
    schd = Schedule.objects.all()
    return render(request, 'schedule.html', {'table' : schd})

story_7/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime, date
from django.urls import reverse

def portofolio(request):
	response = {}
	return render(request, 'portofolio.html', response)

story_8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

def search_book(request):
	response = {}
	return render(request, 'search_book.html', response)

def search(request, title):
	response = requests.get('https://www.googleapis.com/books/v1/volumes?q=intitle:' + title)
	return JsonResponse(response.json())

story_5/templates/add_schedule.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>schedule</title>

	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insanul Fahmi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
</head>
<body>
	{%include "header.html"%}

	<div class="container montserrat_font">
        <h1 class="title_white" style="text-align: right; margin-top: 95px; color: white;">Add Schedule</h1>
        
        <div class="row">
            <div class="col-sm-6 mx-auto" style="margin: 40px 0px">
                <form action="{% url 'story_5:add_schedule' %}" method="POST">
                    {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                    <div class="pull-right">
                        <button type="submit" class="btn btn-secondary" href="{% url 'story_5:schedule' %}">
                            Submit
                        </button>
                        <a class="btn btn-secondary" href="{% url 'story_5:schedule' %}">
                        	See my schedules
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>


</body>
</html>

story_5/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>contact</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insanul Fahmi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</head>
<body>

	{%include "header.html"%}
	
	<div class="container container_contact">
        <div class="row row_contact">
            
        	<div class="col-lg-12">
        		<form action="" method="POST" enctype="multipart/form-data" id="form_id"> 
            		
            		<div class="form-group">
                 		<h5><label for="inputName">Name</label></h5>

                	<input type="text" name="career[name]" class="form-control" tabindex="1" placeholder="Enter your name" pattern="[a-zA-Z. ]{1,50}" required>
            		</div>
            
            		
            		<div class="form-group">
                		<h5><label for="inputEmail">Email</label></h5>

                	<input type="email" name="career[email]" class="form-control" tabindex="2" placeholder="Enter your email address" required>
            		</div>
            
            		
            		<div class="form-group">
                 		<h5><label for="inputMobile">Mobile</label></h5>

                	<input type="tel" name="career[mobile]" class="form-control" tabindex="3" placeholder="Enter your mobile number" pattern="[0-9]{10}" maxlength="10" required>
            		</div>
            
            		
            		<div class="form-group">
                 	<h5><label for="inputMessage">Message</label></h5>

                	<textarea name="career[message]" class="form-control" tabindex="4" placeholder="Write your details" required></textarea>
            
            		<div>
	            		<button type="button" name="submit" class="btn btn-primary btn-block" tabindex="5">
	            			<a href="{% url 'story_5:contact' %}" class="btn-text">submit</a>
	            		</button>
	            	</div>
        		</form>
    		</div>

        </div>
    </div>
</body>
</html>

story_5/templates/header.html
{% load static %}
<div>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="{% url 'story_5:index' %}">
            <img style="height: 50px;" src="{% static 'images/sanwa.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:index' %}#">HOME</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:index' %}#about">ABOUT</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:index' %}#experience">EXPERIENCE</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:index' %}#business">BUSINESS</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:schedule' %}">SCHEDULE</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_8:search_book' %}">BOOK</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story_5:contact' %}">CONTACT</a>
                </li>

            </ul>
        </div>
    </nav>

    <div class="jumbotron text-center" id = "jumbotron_top"></div>
</div>

story_5/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Insanul Fahmi</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
    <style>
        .carousel-item {
            height: 100vh;
            min-height: 350px;
            background: no-repeat center center scroll;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
}
    </style>

    {%include "header.html"%}

<!-- ***********************************-container_1-************************************* -->

    <div class="container container_1">
        <div class="row row_1">
            <div class="col-md-5 px-4 pt-4"> 
                <ul>
                    <li>
                        <h1 class="judul nama">Insanul Fahmi</h1>
                    </li>

                    <li style="margin-top: -10px;">
                        <h1 class="judul aktivitas">Young Entrepreneur</h1>
                    </li>
                </ul>

                <a class="btn btn-secondary" href="{% url 'story_7:portofolio' %}">
                    Portofolio
                </a>
            </div>
        
            <div class="col-md-7 image-insan-1">
              <img class="images image_1" src="{% static 'images/insan_1.png' %}" alt="My image" style="margin-top: 1px;">

            </div>
        </div>
    </div>

<!-- ***********************************-container_2-************************************* -->

    <div id="about" class="container container_2">
        <div class="row row_2">
            <div class="col-md-5 image-insan-2">
                <img class="images image_2" src="{% static 'images/about.jpeg' %}" alt="image">
            </div>

            <div class="col-md-7 isi-about">

                <h1 class="judul about">ABOUT</h1>
                <p class="paragraph_1">Halo! Nama saya Insanul Fahmi, saat ini saya sedang berkuliah di Universitas Indonesia, Fakultas Ilmu Komputer. Selain ngoding, hobi saya yang sedang saya tekuni saat ini yaitu berdagang. Menurut saya berdagang itu seru karena selain mendapatkan uang, saya juga menjadi punya banyak relasi dan selalu berinteraksi dengan sekitar. Soal tujuan berdagang saya mempunyai misi yang sederhana, yaitu membantu umat.</p>

            </div>

        </div>
    </div>

<!-- ***********************************-container_3-************************************* -->

    <div id="experience" class="container container_3">
        <div class="row row_3">

            <div class="col-md-4">
                
            </div>

            <div class="col-md-4">
                <div class="rectangle rectangle_1">
                    <h1 class="judul">EXPERIENCE</h1>
                </div>
                
            </div>

            <div class="col-md-4">
                
            </div>

<!-- ************************************************************************ -->

            <div class="col-md-3">
                
            </div>

<!-- ***********************************-box TK-************************************* -->

            <div class="col-md-6" style="text-align: center;">
                
                <div class="line_vertical line-v-1"></div>
                <div class="circle">
                    <h2 class="sekolah">TK</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">Yayasan Jayawijaya, Tembaga Pura</h6>
                    <h6 class="box-title grey">2003 - 2004</h6>
                    <p class="box-title white">Pada saat TK saya mulai tertarik belajar berhitung. Karena sangking sukanya berhitung orangtua saya memasukan saya ke les sempoa agar kemampuan berhitung saya semakin bertambah.</p>
                </div>

<!-- ***********************************-box SD-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SD</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SD IT Asy-Syammil, Bontang</h6>
                    <h6 class="box-title grey">2004 - 2010</h6>
                    <p class="box-title white">Pada saat SD kelas 2 saya jualan makanan seperti permen dan coklat, 1 hari saya bisa profit 50 ribu. Naik kelas 4 saya jualan mainan dengan profit per hari 150 ribu. Saya tau teman teman saya waktu itu anak-anak, dan itu saya jadikan peluang.</p>
                </div>

<!-- ***********************************-box SMP-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SMP</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SMP IT Al-Fityan, Medan</h6>
                    <h6 class="box-title grey">2011 - 2013</h6>
                    <p class="box-title white">Pada saat SMP saya sangat maniak sekali bermain game. Zaman SMP ini saya lebih banyak transaksi di game online (Trading Item) yang bisa ditukar dalam bentuk uang Cash Rupiah.</p>
                </div>
                
<!-- ***********************************-box SMA-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="circle">
                    <h2 class="sekolah">SMA</h2>
                </div>

                <div class="box box_1">
                    <h6 class="box-title orange">SMA N 3 MEDAN, Medan</h6>
                    <h6 class="box-title grey">2014 - 2017</h6>
                    <p class="box-title white">Berhenti bermain game, pada saat SMA saya mencoba berbagai macam usaha. Salah satunya jualan air mineral dan makanan di sekolah. Satu bulan pendapatan kami (tim) bisa sampai belasan juta.</p>
                </div>

<!-- ***********************************-box KULIAH-************************************* -->

                <div class="line_vertical line-v-1"></div>

                <div class="rectangle rectangle_2">
                    <h2 style="margin-top: -9px">KULIAH</h2>
                </div>

                <div class="box box_4">
                    <h6 class="box-title orange">Univeristy of Indonesia</h6>
                    <p class="box-title white">Berhenti bermimpi dan bangun untuk mewujudkan mimpi tersebut. Selama 16 tahun jiwa entrepreneurku telah kuasah, maka sudah bukan saatnya bermain main lagi. Sebelum kami bangun bersama sama bisnis ini (tim). Aku mulai semuanya dengan banyak kegagalan, namun aku tahu itu hanya hanya proses menuju kesuksesan. “Tugas manusia hanya berikhtiar, hasilnya hanya Allah yang menentukan.” - Sanwa Store</p>
                </div>

<!-- ************************************************************************ -->

            </div>

            <div class="col-md-3">
                
            </div>
        </div>
    </div>


<!-- ***********************************-container_4-************************************* -->
        
    <div id="business" class="container-fluid container_4">
        <div class="row">
            <div class="col-md-12">
                <div class="gambar text-center">
                    <img class="images image_3" src="{% static 'images/kurma2.jpeg' %}" alt="image">
                </div>
            </div>

<!-- ********************************************************************* -->
    
            <div class="col-md-5 text-center">
                <div>
                    <h1 class="judul_business">BUSINESS</h1>
                </div>

                <div>
                    <img class="images image_4" src="{% static 'images/sanwa.png' %}" alt="image">
                </div>

                <div class="orange_box_left">
                <p class="orange_title_left">Berawal dari membuka toko baju, Sanwa Store yang saat ini sudah berdiri sejak bulan Februari 2019 lebih memilih untuk fokus memenuhi kebutuhan masyarakat  berupa barang - barang yang diimport dari luar Indonesia. Khususnya saat ini untuk kebutuhan kesehatan masyarakat Indonesia. Setiap penjualanan, Sanwa Store menyalurkan donasi sebesar 5% profit untuk Masyarakat Indonesia yang membutuhkan. Belanja di Sanwa Store sama dengan berdonasi 5%.</p>
                </div>
            
            </div>

            <div class="col-md-2 text-center">
                <ul>
                    <li style="text-shadow: 1px 1px 3px; margin-top: 70px;">
                        <h6>PRODUK</h6>
                    </li>
                        
                    <li style="color: white; text-shadow: 1px 1px 5px #000000; margin-top: 20px;">
                        <h6>Kurma Ajwah</h6>
                    </li>

                    <li style="color: white; text-shadow: 1px 1px 5px #000000;">
                        <h6>Saffron Kashmir</h6>
                    </li>
                </ul>
            </div>

            <div class="col-md-5 text-center">
                
                <div style="margin-top: 65px;">
                    <ul>
                        <li><img class="images image_5" src="{% static 'images/gmail.png' %}" alt="image"></li>
                        <li><img class="images image_6" src="{% static 'images/instagram.png' %}" alt="image"></li>
                        <li><img class="images image_7" src="{% static 'images/whatsapp.png' %}" alt="image"></li>
                    </ul>
                </div>

                <div>
                    <ul class="list_sanwastore text-center">
                        <li style="padding-bottom: 27px;">sanwa.toko@gmail.com</li>
                        <li style="padding-bottom: 27px;">@sanwa.store</li>
                        <li>+6287896438982</li>
                    </ul>
                </div>
            
            </div>

    
            <div class="background_orange_1"></div>

        </div>
    </div>


<!-- ***********************************-container_5-************************************* -->
    <div class="container container_5 text-center">
        
        <div class="row">
            <div class="col-md-12">
                
                <div>
                    <h1 class="judul_contact text-center">CONTACT</h1>
                </div>

                <div>
                <p class="title_contact text-center">Hubungi saya jika ingin mengetahui bisnis yang saya dirikan!</p>
                </div>

                <div class="button_contact">
                    <button type="button" class="btn btn-secondary">
                        <a href="{% url 'story_5:contact' %}" class="btn-text">hubungi saya</a>
                    </button>
                </div>

                <div>
                    <h6 style="font-size: 13px; margin-top: 50px;">© Insanul Fahmi</h6>
                </div>

            </div>

        </div>

        <div class="container background_orange_2"></div>
    </div>

</body>
</html>

story_5/templates/schedule.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>schedule</title>

	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Insanul Fahmi</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
</head>
<body>
	{%include "header.html"%}
    <div class="container montserrat_font">
    <h1 class="title_white" style="margin-top: 90px; color: white;">Schedule list</h1>
      
      <table id='mySchedule' class="table table-striped table-light" style="margin-top: 40px">
          <thead>
            <tr>
                <th scope="col">Kegiatan</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Hari</th>
                <th scope="col">Jam</th>
                <th scope="col">Tempat</th>
                <th scope="col">Kategori</th>
            </tr>
          </thead>
          
          <tbody>
            {% for schedule in table %}
            <tr>
              <th scope="row">{{ schedule.nama_kegiatan }}</th>
              <td>{{ schedule.tanggal }}</td>
              <td>{{ schedule.hari }}</td>
              <td>{{ schedule.jam }}</td>
              <td>{{ schedule.tempat }}</td>
              <td>{{ schedule.kategori }}</td>
              <td>
                <a class="btn btn-secondary" href="{% url 'story_5:deleteList' schedule.id %}">
                  delete
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
      </table>
      
      <div style="padding-bottom:200px">
        <a class="btn btn-info float-right" href="{% url 'story_5:add_schedule' %}">
          Add schedule
        </a>
      </div>
    </div>

</body>
</html>

story_7/templates/portofolio.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>portofolio</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_sanwastore.css' %}" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
	<script src="{% static 'js/portofolio.js' %}"></script>

	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
  	<script src="//code.jquery.com/jquery-1.12.4.js"></script>
  	<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<body>

	<div class="container-fluid header text-center">
		<b id="judul" class="judul-portofolio">PORTOFOLIO</b>
	</div>


	<div class="container theme-mode-button text-center">
		<button id="button1" class="btn btn-secondary">
		Dark Mode</button>

	</div>

	<div id="box" class="container background-box">
		
		<div class="accordion-container">

  			<div class="set">
    			<a href="#">Aktivitas</a>
    
    			<div class="content">
      				<ul>
      					<li>- Kuliah</li>
      					<li>- Berbisnis</li>
      				</ul>
    			</div>
  			</div>
  

	  		<div class="set">
	    		<a href="#">Pengalaman Organisasi/Kepanitiaan</a>
	    		
	    		<div class="content">
	      			<ul>
      					<li>- Magang BEM media fasilkom</li>
      					<li>- Magang DPM wirus fasilkom</li>
      					<li>- PJ dokum angkatan</li>
      					<li>- Dokumentasi OH Fasilkom (Humas)</li>
      				</ul>
	    		</div>
			</div>
  

	  		<div class="set">
	    		<a href="#">Prestasi</a>

	    		<div class="content">
	      			<p>---</p>
	    		</div>
	  		</div>
  
		</div>
	</div>

	<div class="container-fluid footer text-center">
		<p id="text-ftr" class="text-footer centered">©️ 2019 PPW - Insanul Fahmi</p>
	</div>

</body>
</html>